### ISSUE TITLE
more examples 

### ISSUE THREAD

**Issue by Restry** [ctlllll/LLM-ToolMaker#3]
Your project is fantastic, and I feel inspired by it. I believe this tool can be used for many interesting functionalities. For example, it could generate various tools based on natural language and allow users to invoke them automatically based on relevant contexts.

but i dont't know how to use it ... 😅😅
Do you have any examples of such applications?

**Comment by Bleach4Ever** [comment]
me too

**Comment by GithungDang** [comment]
me too.
and i want to play it on llama's models or rwkv

**Comment by ctlllll** [comment]
Thanks for your interest! The basic function of determining which existing tool to use and invoking ToolMaker to make new tools when needed is implemented by the Dispatcher (Please see Figure 4 in the paper, and also https://github.com/ctlllll/LLM-ToolMaker/blob/main/tooluser.ipynb). We are working on making the method more general and would appreciate any community contributions and discussions :)
