### ISSUE TITLE
Question about your observation in the paper

### ISSUE THREAD

**Issue by qfkkwgd** [ctlllll/LLM-ToolMaker#4]
Hi authors,

In Page 8, section 4.5, you mentioned "we found that models that before instruction tuning often perform better than their counterparts post instruction tuning".

From my observation, the trend in Table 4 is GPT3.5 > text-davinci-002 > davinci > curie > babbage > ada. I wonder how you arrive the above observation.

**Comment by ctlllll** [comment]
Hi, thanks for your interest! The argument you mentioned is about GPT-3 series of models, and our observation was ada > text-ada-001 (instruction-tuned ada). We'll make the argument clearer in the next version.
